#
# Created by Samuel Dufresne on 2018-04-14
#

CONST_USER_ID = 'OnrOomBTBWVMMD2scVWbqCSlnTQ2'

CONST_SPLIT_BY_DAYS_TRAINING_DAYS = {'2018-4-13': True, '2018-4-9': True, '2018-4-14': True, '2018-4-15': True, '2018-4-12': True, '2018-4-10': True, '2018-4-11': True}

CONST_SPLIT_BY_DAYS_EXERCISES = {'upper': ['bent over barbell row', 'seated one-arm cable pulley rows', 'spinal stretch', 'smith machine bent over row', 'lower back-smr', 'lower back-smr', 'smith machine bent over row', 'two-arm kettlebell row'], 'lower': ['butt lift (bridge)', 'hip lift with band', 'pull through', 'single leg glute bridge', 'butt lift (bridge)', 'hip extension with bands', 'hip extension with bands', 'lying bent leg groin'], 'aerobic': ['running', 'running', 'walking', 'walking', 'walking', 'swimming', 'bicycling'], 'flexibility': ['Bridge With Leg Reach', 'Bridge With Leg Reach', 'Hip circles and twists', 'Single Leg Hamstring', 'glute stretch', 'Bridge With Leg Reach', 'Hip circles and twists']}

CONST_SPLIT_BY_DAYS_RESULT = {'2018-4-13': {'upper': ['bent over barbell row', 'two-arm kettlebell row'], 'lower': ['butt lift (bridge)', 'lying bent leg groin'], 'aerobic': ['running'], 'flexibility': ['Bridge With Leg Reach']}, '2018-4-9': {'upper': ['seated one-arm cable pulley rows'], 'lower': ['hip lift with band'], 'aerobic': ['running'], 'flexibility': ['Bridge With Leg Reach']}, '2018-4-14': {'upper': ['spinal stretch'], 'lower': ['pull through'], 'aerobic': ['walking'], 'flexibility': ['Hip circles and twists']}, '2018-4-15': {'upper': ['smith machine bent over row'], 'lower': ['single leg glute bridge'], 'aerobic': ['walking'], 'flexibility': ['Single Leg Hamstring']}, '2018-4-12': {'upper': ['lower back-smr'], 'lower': ['butt lift (bridge)'], 'aerobic': ['walking'], 'flexibility': ['glute stretch']}, '2018-4-10': {'upper': ['lower back-smr'], 'lower': ['hip extension with bands'], 'aerobic': ['swimming'], 'flexibility': ['Bridge With Leg Reach']}, '2018-4-11': {'upper': ['smith machine bent over row'], 'lower': ['hip extension with bands'], 'aerobic': ['bicycling'], 'flexibility': ['Hip circles and twists']}}

CONST_BUILD_JSON_EXERCISES = {'2018-4-13': {'upper': ['upright row - with bands', 'circus bell'], 'lower': ['standing soleus and achilles stretch', 'squats - with bands'], 'aerobic': ['bicycling'], 'flexibility': ['Standing Calf']}, '2018-4-9': {'upper': ['smith machine upright row'], 'lower': ['posterior tibialis stretch'], 'aerobic': ['walking'], 'flexibility': ['Triceps Stretch']}, '2018-4-14': {'upper': ['upright row - with bands'], 'lower': ['peroneals stretch'], 'aerobic': ['swimming'], 'flexibility': ['Reclining Pigeon']}, '2018-4-15': {'upper': ['standing dumbbell upright row'], 'lower': ['anterior tibialis-smr'], 'aerobic': ['swimming'], 'flexibility': ['Triceps Stretch']}, '2018-4-12': {'upper': ['backward medicine ball throw'], 'lower': ['recumbent bike'], 'aerobic': ['swimming'], 'flexibility': ['Triceps Stretch']}, '2018-4-10': {'upper': ['power partials'], 'lower': ['seated calf stretch'], 'aerobic': ['running'], 'flexibility': ['Standing Calf']}, '2018-4-11': {'upper': ['shoulder circles'], 'lower': ['weighted squat'], 'aerobic': ['bicycling'], 'flexibility': ['Standing Calf']}}

CONST_BUILD_JSON_RESULT = {'2018-4-13': {'upper': {0: {'name': 'upright row - with bands', 'complete': False}, 1: {'name': 'circus bell', 'complete': False}}, 'lower': {0: {'name': 'standing soleus and achilles stretch', 'complete': False}, 1: {'name': 'squats - with bands', 'complete': False}}, 'aerobic': {0: {'name': 'bicycling', 'complete': False}}, 'flexibility': {0: {'name': 'Standing Calf', 'complete': False}}}, '2018-4-9': {'upper': {0: {'name': 'smith machine upright row', 'complete': False}}, 'lower': {0: {'name': 'posterior tibialis stretch', 'complete': False}}, 'aerobic': {0: {'name': 'walking', 'complete': False}}, 'flexibility': {0: {'name': 'Triceps Stretch', 'complete': False}}}, '2018-4-14': {'upper': {0: {'name': 'upright row - with bands', 'complete': False}}, 'lower': {0: {'name': 'peroneals stretch', 'complete': False}}, 'aerobic': {0: {'name': 'swimming', 'complete': False}}, 'flexibility': {0: {'name': 'Reclining Pigeon', 'complete': False}}}, '2018-4-15': {'upper': {0: {'name': 'standing dumbbell upright row', 'complete': False}}, 'lower': {0: {'name': 'anterior tibialis-smr', 'complete': False}}, 'aerobic': {0: {'name': 'swimming', 'complete': False}}, 'flexibility': {0: {'name': 'Triceps Stretch', 'complete': False}}}, '2018-4-12': {'upper': {0: {'name': 'backward medicine ball throw', 'complete': False}}, 'lower': {0: {'name': 'recumbent bike', 'complete': False}}, 'aerobic': {0: {'name': 'swimming', 'complete': False}}, 'flexibility': {0: {'name': 'Triceps Stretch', 'complete': False}}}, '2018-4-10': {'upper': {0: {'name': 'power partials', 'complete': False}}, 'lower': {0: {'name': 'seated calf stretch', 'complete': False}}, 'aerobic': {0: {'name': 'running', 'complete': False}}, 'flexibility': {0: {'name': 'Standing Calf', 'complete': False}}}, '2018-4-11': {'upper': {0: {'name': 'shoulder circles', 'complete': False}}, 'lower': {0: {'name': 'weighted squat', 'complete': False}}, 'aerobic': {0: {'name': 'bicycling', 'complete': False}}, 'flexibility': {0: {'name': 'Standing Calf', 'complete': False}}}}
